def multiplication(NUMBER1,NUMBER2):
    print(NUMBER1 * NUMBER2)

def DIVISION(NUMBER1,NUMBER2):
    print(NUMBER1 / NUMBER2)

def ADDITION(NUMBER1,NUMBER2):
    print(NUMBER1 + NUMBER2)

def SUBSTRACTION(NUMBER1,NUMBER2):
    print(NUMBER1 - NUMBER2)